//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputAction/Player/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""11eeb6ec-b100-4497-8dc9-675a25082104"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""807ce481-fd5f-44f9-a37b-8681b095932a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""1c4f2c5e-a8bd-4465-8e09-a39324092972"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""0b0141ce-4d9b-451e-9391-606a0682f102"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""549cc884-a982-4e98-a060-1094974ed278"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-0.1,max=0.1),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""072c353c-12b0-43ed-8640-8ac9dcc5d907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""3b895e7c-9732-45e6-9f0b-8d9327265b2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b3fb308f-9bab-49ae-be2e-34662e127d0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""ada52c91-9c55-4c6d-ba6b-71b724617f11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Combo"",
                    ""type"": ""Button"",
                    ""id"": ""0aa4ded2-9010-4082-821c-759eb9dd48ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementWithoutNormalization"",
                    ""type"": ""Value"",
                    ""id"": ""e590bd65-952d-42a5-9893-fa482d97892c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""0482f8e6-a73e-49fa-a2ca-b98bf58537ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Locked"",
                    ""type"": ""Button"",
                    ""id"": ""0dc6a6f7-d84f-42ce-b8cc-c35e232c344e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstSkillCast"",
                    ""type"": ""Button"",
                    ""id"": ""e8885f21-b3f7-4b63-bb2c-ac0149ec5b1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSkillCast"",
                    ""type"": ""Button"",
                    ""id"": ""2688a63a-24f3-4808-af5d-574e16afa54f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSkillCast"",
                    ""type"": ""Button"",
                    ""id"": ""6281eeb6-b47f-4fa7-a0b8-128a51a02503"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthSkillCast"",
                    ""type"": ""Button"",
                    ""id"": ""c1642e9c-57eb-40ba-a170-867310d5104d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstItem"",
                    ""type"": ""Button"",
                    ""id"": ""01ac6e7f-232a-4743-9f1c-021ea7e667df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondItem"",
                    ""type"": ""Button"",
                    ""id"": ""548ea7d7-4a89-4c3f-b4bd-77ceb57a9997"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdItem"",
                    ""type"": ""Button"",
                    ""id"": ""2c2d09a0-8d56-4c7a-ac08-17fe24551e98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthItem"",
                    ""type"": ""Button"",
                    ""id"": ""685e318b-4f64-4fb1-b285-a63cbc6c9cc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9d5bc40e-45d9-4477-b07f-e59afcc201d9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f0f11718-bf64-4d0e-9692-8f1fc611e445"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1f0ac9d4-3837-4eed-8f46-baf8f255c11b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3daf5be5-c6ee-4312-a7e0-a23ce4d28c64"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""efd286f6-11d4-4b46-887e-2db36494d9e0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""17bee589-f625-499c-bded-9e64e620b222"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f0429a06-69cf-40b8-aeb3-2ee3204562b8"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66620bb6-586e-414c-960c-8d49af5dd753"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b7032c2-2232-4e24-9278-d55357e5d6af"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df988a47-c965-4b0e-883c-ad47ff082923"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32b48067-252f-4f60-88f3-d7415dbc0f9b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfedcd3a-a252-4a14-943e-0d69302cfa5d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cdc6bbf-1284-4d98-8e84-68fd453f0df6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""566f7d06-3420-48f6-adf1-c2ea3ed0ee5c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb16d3a5-c6f9-45c8-bc21-846a3302baff"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Combo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ffbee6ef-7dc5-43c6-a869-12235753753b"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWithoutNormalization"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d35b0e0a-cc83-4909-80af-5bd8cb209eb7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWithoutNormalization"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cbb6f363-b721-4805-b56b-6bfc7fe94890"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWithoutNormalization"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4301cb5d-da7d-44ea-9bcc-4979fd6e8925"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWithoutNormalization"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c178ac31-d747-474b-b7be-bf8c3ee0f573"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWithoutNormalization"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""14fc486f-71e2-4d8d-979d-adb898bf6f24"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87956a26-e21f-4de8-bc7b-e51848aa930f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Locked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""813023a6-7159-47f3-a9dc-431254f4b54f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSkillCast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c5e448b-7da9-4ff8-8bab-44578f85350d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSkillCast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee80abf2-725b-4a6f-9074-0f8bcff9a01c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSkillCast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5116ea5-9774-4f8e-aa92-d57d90328ee5"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthSkillCast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3118d8d0-a5da-44d0-b031-e66b0303de08"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90814409-3a88-4ace-b630-608ea42be5bd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c13a529-6a2d-4842-9452-2e5a9a8f37b7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35bddf70-b293-4c28-a017-0b6a29088d85"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Bar"",
            ""id"": ""e22bdeea-72b8-4ed2-bb37-475478284c53"",
            ""actions"": [
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""fbddf2a9-ec46-4130-8990-1ec70801f6ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop"",
                    ""type"": ""Button"",
                    ""id"": ""11b86e5a-0ab1-43f2-8ae1-313d83fc2afa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skills"",
                    ""type"": ""Button"",
                    ""id"": ""463aa9d4-811e-42d0-a6a3-839ac31f0d46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quests"",
                    ""type"": ""Button"",
                    ""id"": ""1d3d0727-049e-4ef4-9f12-c4d4b44ac6e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fight"",
                    ""type"": ""Button"",
                    ""id"": ""2f42d823-2df4-4fb1-84f6-7e14da53e08a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""086e130c-5d24-4e55-ac1c-4d41125ad2e2"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3f4f228-53df-4686-b808-e895204f4c1a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd031f1a-146c-4665-a311-92e402d3c17b"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""904095fb-838e-4b7e-9efe-1ac06d2cdb5a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quests"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""967c7b8f-71e3-4e36-86a3-efbf13f59df5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Walk = m_Player.FindAction("Walk", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Zoom = m_Player.FindAction("Zoom", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Combo = m_Player.FindAction("Combo", throwIfNotFound: true);
        m_Player_MovementWithoutNormalization = m_Player.FindAction("MovementWithoutNormalization", throwIfNotFound: true);
        m_Player_Roll = m_Player.FindAction("Roll", throwIfNotFound: true);
        m_Player_Locked = m_Player.FindAction("Locked", throwIfNotFound: true);
        m_Player_FirstSkillCast = m_Player.FindAction("FirstSkillCast", throwIfNotFound: true);
        m_Player_SecondSkillCast = m_Player.FindAction("SecondSkillCast", throwIfNotFound: true);
        m_Player_ThirdSkillCast = m_Player.FindAction("ThirdSkillCast", throwIfNotFound: true);
        m_Player_FourthSkillCast = m_Player.FindAction("FourthSkillCast", throwIfNotFound: true);
        m_Player_FirstItem = m_Player.FindAction("FirstItem", throwIfNotFound: true);
        m_Player_SecondItem = m_Player.FindAction("SecondItem", throwIfNotFound: true);
        m_Player_ThirdItem = m_Player.FindAction("ThirdItem", throwIfNotFound: true);
        m_Player_FourthItem = m_Player.FindAction("FourthItem", throwIfNotFound: true);
        // Bar
        m_Bar = asset.FindActionMap("Bar", throwIfNotFound: true);
        m_Bar_Inventory = m_Bar.FindAction("Inventory", throwIfNotFound: true);
        m_Bar_Shop = m_Bar.FindAction("Shop", throwIfNotFound: true);
        m_Bar_Skills = m_Bar.FindAction("Skills", throwIfNotFound: true);
        m_Bar_Quests = m_Bar.FindAction("Quests", throwIfNotFound: true);
        m_Bar_Fight = m_Bar.FindAction("Fight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Walk;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Zoom;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Combo;
    private readonly InputAction m_Player_MovementWithoutNormalization;
    private readonly InputAction m_Player_Roll;
    private readonly InputAction m_Player_Locked;
    private readonly InputAction m_Player_FirstSkillCast;
    private readonly InputAction m_Player_SecondSkillCast;
    private readonly InputAction m_Player_ThirdSkillCast;
    private readonly InputAction m_Player_FourthSkillCast;
    private readonly InputAction m_Player_FirstItem;
    private readonly InputAction m_Player_SecondItem;
    private readonly InputAction m_Player_ThirdItem;
    private readonly InputAction m_Player_FourthItem;
    public struct PlayerActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Walk => m_Wrapper.m_Player_Walk;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Zoom => m_Wrapper.m_Player_Zoom;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Combo => m_Wrapper.m_Player_Combo;
        public InputAction @MovementWithoutNormalization => m_Wrapper.m_Player_MovementWithoutNormalization;
        public InputAction @Roll => m_Wrapper.m_Player_Roll;
        public InputAction @Locked => m_Wrapper.m_Player_Locked;
        public InputAction @FirstSkillCast => m_Wrapper.m_Player_FirstSkillCast;
        public InputAction @SecondSkillCast => m_Wrapper.m_Player_SecondSkillCast;
        public InputAction @ThirdSkillCast => m_Wrapper.m_Player_ThirdSkillCast;
        public InputAction @FourthSkillCast => m_Wrapper.m_Player_FourthSkillCast;
        public InputAction @FirstItem => m_Wrapper.m_Player_FirstItem;
        public InputAction @SecondItem => m_Wrapper.m_Player_SecondItem;
        public InputAction @ThirdItem => m_Wrapper.m_Player_ThirdItem;
        public InputAction @FourthItem => m_Wrapper.m_Player_FourthItem;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Walk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Zoom.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoom;
                @Dash.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Combo.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCombo;
                @Combo.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCombo;
                @Combo.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCombo;
                @MovementWithoutNormalization.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementWithoutNormalization;
                @MovementWithoutNormalization.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementWithoutNormalization;
                @MovementWithoutNormalization.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementWithoutNormalization;
                @Roll.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @Locked.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLocked;
                @Locked.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLocked;
                @Locked.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLocked;
                @FirstSkillCast.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstSkillCast;
                @FirstSkillCast.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstSkillCast;
                @FirstSkillCast.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstSkillCast;
                @SecondSkillCast.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondSkillCast;
                @SecondSkillCast.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondSkillCast;
                @SecondSkillCast.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondSkillCast;
                @ThirdSkillCast.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdSkillCast;
                @ThirdSkillCast.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdSkillCast;
                @ThirdSkillCast.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdSkillCast;
                @FourthSkillCast.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthSkillCast;
                @FourthSkillCast.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthSkillCast;
                @FourthSkillCast.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthSkillCast;
                @FirstItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstItem;
                @FirstItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstItem;
                @FirstItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstItem;
                @SecondItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondItem;
                @SecondItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondItem;
                @SecondItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondItem;
                @ThirdItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdItem;
                @ThirdItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdItem;
                @ThirdItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdItem;
                @FourthItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthItem;
                @FourthItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthItem;
                @FourthItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthItem;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Combo.started += instance.OnCombo;
                @Combo.performed += instance.OnCombo;
                @Combo.canceled += instance.OnCombo;
                @MovementWithoutNormalization.started += instance.OnMovementWithoutNormalization;
                @MovementWithoutNormalization.performed += instance.OnMovementWithoutNormalization;
                @MovementWithoutNormalization.canceled += instance.OnMovementWithoutNormalization;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @Locked.started += instance.OnLocked;
                @Locked.performed += instance.OnLocked;
                @Locked.canceled += instance.OnLocked;
                @FirstSkillCast.started += instance.OnFirstSkillCast;
                @FirstSkillCast.performed += instance.OnFirstSkillCast;
                @FirstSkillCast.canceled += instance.OnFirstSkillCast;
                @SecondSkillCast.started += instance.OnSecondSkillCast;
                @SecondSkillCast.performed += instance.OnSecondSkillCast;
                @SecondSkillCast.canceled += instance.OnSecondSkillCast;
                @ThirdSkillCast.started += instance.OnThirdSkillCast;
                @ThirdSkillCast.performed += instance.OnThirdSkillCast;
                @ThirdSkillCast.canceled += instance.OnThirdSkillCast;
                @FourthSkillCast.started += instance.OnFourthSkillCast;
                @FourthSkillCast.performed += instance.OnFourthSkillCast;
                @FourthSkillCast.canceled += instance.OnFourthSkillCast;
                @FirstItem.started += instance.OnFirstItem;
                @FirstItem.performed += instance.OnFirstItem;
                @FirstItem.canceled += instance.OnFirstItem;
                @SecondItem.started += instance.OnSecondItem;
                @SecondItem.performed += instance.OnSecondItem;
                @SecondItem.canceled += instance.OnSecondItem;
                @ThirdItem.started += instance.OnThirdItem;
                @ThirdItem.performed += instance.OnThirdItem;
                @ThirdItem.canceled += instance.OnThirdItem;
                @FourthItem.started += instance.OnFourthItem;
                @FourthItem.performed += instance.OnFourthItem;
                @FourthItem.canceled += instance.OnFourthItem;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Bar
    private readonly InputActionMap m_Bar;
    private IBarActions m_BarActionsCallbackInterface;
    private readonly InputAction m_Bar_Inventory;
    private readonly InputAction m_Bar_Shop;
    private readonly InputAction m_Bar_Skills;
    private readonly InputAction m_Bar_Quests;
    private readonly InputAction m_Bar_Fight;
    public struct BarActions
    {
        private @PlayerInputAction m_Wrapper;
        public BarActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Inventory => m_Wrapper.m_Bar_Inventory;
        public InputAction @Shop => m_Wrapper.m_Bar_Shop;
        public InputAction @Skills => m_Wrapper.m_Bar_Skills;
        public InputAction @Quests => m_Wrapper.m_Bar_Quests;
        public InputAction @Fight => m_Wrapper.m_Bar_Fight;
        public InputActionMap Get() { return m_Wrapper.m_Bar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BarActions set) { return set.Get(); }
        public void SetCallbacks(IBarActions instance)
        {
            if (m_Wrapper.m_BarActionsCallbackInterface != null)
            {
                @Inventory.started -= m_Wrapper.m_BarActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_BarActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_BarActionsCallbackInterface.OnInventory;
                @Shop.started -= m_Wrapper.m_BarActionsCallbackInterface.OnShop;
                @Shop.performed -= m_Wrapper.m_BarActionsCallbackInterface.OnShop;
                @Shop.canceled -= m_Wrapper.m_BarActionsCallbackInterface.OnShop;
                @Skills.started -= m_Wrapper.m_BarActionsCallbackInterface.OnSkills;
                @Skills.performed -= m_Wrapper.m_BarActionsCallbackInterface.OnSkills;
                @Skills.canceled -= m_Wrapper.m_BarActionsCallbackInterface.OnSkills;
                @Quests.started -= m_Wrapper.m_BarActionsCallbackInterface.OnQuests;
                @Quests.performed -= m_Wrapper.m_BarActionsCallbackInterface.OnQuests;
                @Quests.canceled -= m_Wrapper.m_BarActionsCallbackInterface.OnQuests;
                @Fight.started -= m_Wrapper.m_BarActionsCallbackInterface.OnFight;
                @Fight.performed -= m_Wrapper.m_BarActionsCallbackInterface.OnFight;
                @Fight.canceled -= m_Wrapper.m_BarActionsCallbackInterface.OnFight;
            }
            m_Wrapper.m_BarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Shop.started += instance.OnShop;
                @Shop.performed += instance.OnShop;
                @Shop.canceled += instance.OnShop;
                @Skills.started += instance.OnSkills;
                @Skills.performed += instance.OnSkills;
                @Skills.canceled += instance.OnSkills;
                @Quests.started += instance.OnQuests;
                @Quests.performed += instance.OnQuests;
                @Quests.canceled += instance.OnQuests;
                @Fight.started += instance.OnFight;
                @Fight.performed += instance.OnFight;
                @Fight.canceled += instance.OnFight;
            }
        }
    }
    public BarActions @Bar => new BarActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnCombo(InputAction.CallbackContext context);
        void OnMovementWithoutNormalization(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnLocked(InputAction.CallbackContext context);
        void OnFirstSkillCast(InputAction.CallbackContext context);
        void OnSecondSkillCast(InputAction.CallbackContext context);
        void OnThirdSkillCast(InputAction.CallbackContext context);
        void OnFourthSkillCast(InputAction.CallbackContext context);
        void OnFirstItem(InputAction.CallbackContext context);
        void OnSecondItem(InputAction.CallbackContext context);
        void OnThirdItem(InputAction.CallbackContext context);
        void OnFourthItem(InputAction.CallbackContext context);
    }
    public interface IBarActions
    {
        void OnInventory(InputAction.CallbackContext context);
        void OnShop(InputAction.CallbackContext context);
        void OnSkills(InputAction.CallbackContext context);
        void OnQuests(InputAction.CallbackContext context);
        void OnFight(InputAction.CallbackContext context);
    }
}
